### ISSUE TITLE
Change allowlist minting duration to 48 hours

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/mgguild.github.io#100]
Since there are no waitlist spots, we will adjust the minting duration of allowlist spots
From 24 hours -> 48 hours

**Allowlist:**
Start: August 23, 2022 12PM GMT+8
End: August 25, 2022 12PM GMT+8

_**General Public**_
Start: August 25, 2022 12PM GMT+8
End: No end date, as long as there is a supply

Also change the date:
![image](https://user-images.githubusercontent.com/57949551/186048832-bb5537bc-f695-4c19-9f6b-1934dff8858c.png)
August 23, 2022 12PM GMT+8

**Comment by aldrickb** [comment]
Contract updates done:
https://etherscan.io/tx/0x74df7dbe966e67ec47ac4a0515c4485eec11283d851827899768b117f962aeb4
https://etherscan.io/tx/0x04215ac7906e3a524602e102ef97f89b544439ac6be0c6380d6f720e5a2b0a7d
https://etherscan.io/tx/0x54602d6718e44cd5becb3ba22eec0fbb2c17a5e66b5e4411c41a92065ffb92cc
