### ISSUE TITLE
Prepare MGG PFP NFTs contract

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/mgguild.github.io#95]

**Comment by aldrickb** [comment]
**RINKEBY TESTNET:**

**Minting Contract for MetaGaming PFP NFTs (Rinkeby) (This contract contains the buy function)**
https://rinkeby.etherscan.io/address/0xaA71113164F2c1E2f1c7Eb29Fa828501B9D1ca05

**NFT Contract For MetaGaming PFP NFTs (The actual NFT contract)**
https://rinkeby.etherscan.io/address/0x2957b3c84BFa0daAcCb2902aC59f4f0C0694f555

**OPENSEA URL (TESTNET)**
https://testnets.opensea.io/assets/rinkeby/0x2957b3c84bfa0daaccb2902ac59f4f0c0694f555/5

**Comment by aldrickb** [comment]
### ETHEREUM MAINNET: 

**Minting Contract for MetaGaming PFP NFTs (This contract contains the buy function)**
https://etherscan.io/address/0xE716f661051C026bc9fE40bca5F8443aCe5a7b13

**NFT Contract For MetaGaming PFP NFTs (The actual NFT contract)**
https://etherscan.io/address/0xB88471E77b195aBa10068960ac83AC8c6983013F

**OPENSEA URL**
https://opensea.io/assets/ethereum/0xB88471E77b195aBa10068960ac83AC8c6983013F/1

**Comment by medardm** [comment]
OPENSEA Testnet url: 
https://testnets.opensea.io/assets/rinkeby/0x2957b3c84BFa0daAcCb2902aC59f4f0C0694f555/1

**Comment by aldrickb** [comment]
Re-updated ETHEREUM MAINNET addresses
